Repository jerryscript-project/iotjs, pull requests merged in 2018-06, with the labels that each got.

#1681 Fix features list in 'iotjs_build_info.js'.
  test/testsets.json
  test/tools/iotjs_build_info.js
Labels: bug

#1683 Rework the timeout detection in the testrunner
  tools/testrunner.py
Labels: infrastructure

#1686 Removed 'iotjs_jhelper_call' function from bindings.
  src/iotjs_binding.c
  src/iotjs_binding.h
  src/iotjs_binding_helper.c
  src/iotjs_binding_helper.h
  src/modules/iotjs_module_tcp.c
  src/modules/iotjs_module_uart.c
  src/modules/linux/iotjs_module_blehcisocket-linux.c
  src/modules/linux/iotjs_module_gpio-linux.c
Labels: binding, enhancement
